apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: gettix-dev-362722
  artifacts:
    - image: ajosemalik/gettix-auth
      # - image: us.gcr.io/gettix-dev-362722/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: ajosemalik/gettix-client
      # - image: us.gcr.io/gettix-dev-362722/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'client/**/*.js'
    - image: ajosemalik/gettix-tickets
      # - image: us.gcr.io/gettix-dev-362722/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: ajosemalik/gettix-orders
      # - image: us.gcr.io/gettix-dev-362722/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
