apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: ajosemalik/gettix-auth
        # image: us.gcr.io/gettix-dev-362722/auth
        env:
        - name: MONGO_URI
          value: 'mongodb://auth-mongo-service:27017/auth'
        - name: JWT_GETTIX_KEY
          valueFrom:
            secretKeyRef: 
              name: jwt-gettix
              key: JWT_GETTIX_KEY
        resources:
          limits:
            memory: "600Mi"
            cpu: "600m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
  - name: auth
    protocol: TCP
    port: 3000
    targetPort: 3000
