apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: ajosemalik/gettix-payments
        # image: us.gcr.io/gettix-dev-362722/payments
        env:
        - name: NATS_CLIENT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NATS_URL
          value: 'http://nats-service:4222'
        - name: NATS_CLUSTER_ID
          value: gettix
        - name: MONGO_URI
          value: 'mongodb://payments-mongo-service:27017/payments'
        - name: JWT_GETTIX_KEY
          valueFrom:
            secretKeyRef: 
              name: jwt-gettix
              key: JWT_GETTIX_KEY
        resources:
          limits:
            memory: "600Mi"
            cpu: "600m"
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  selector:
    app: payments
  ports:
  - name: payments
    protocol: TCP
    port: 3000
    targetPort: 3000
